services:
  stempel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitaler-stempel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stempel.rule=Host(`pruefstempel.wuppt.de`)"
      - "traefik.http.routers.stempel.entrypoints=https"
      - "traefik.http.routers.stempel.tls.certresolver=cloudflare"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
